### ISSUE TITLE
Add first blog post

### ISSUE THREAD

**Issue by julienbrg** [julienbrg/personal-website#3]

**Comment by julienbrg** [comment]
- re-edit

**Comment by batu07040** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
flyq, @Trixie2993, @zakaria5313, @iriniStrangeloop, @z4cki, @CristianRicharte6, @Pikkuherkko, @0xhelium, @KristianPeter, @William-dev1992, @xiaol0ng, @qy3u, @yanukadeneth99, @mbukeRepo, @suckitfa, @Avalonk19, @yzhaoyu, @cocacolasante, @h33min, @Y4CN, @fuchan1, @al-ias, @Unzerror, @geoffreysy, @CeerDecy, @jneygor8504, @inrust, @wangxianqi, @Ifechukwudaniel, @debuggingfuture-animoca, @LyttonPrime, @yasin-cs-ko-ak, @ikhana, @jhmehdi79, @ben-meyer, @wtakaman, @havingautism, @vuldavan, @franktomass, @CallumBicknell, @21fahm, @jeronimoalbi, @Saszr, @liuzjalex, @utx0, @dasibcryptoidology, @tjordy17, @tannakartikey, @nir-zilberman, @flackoon

**Comment by batu07040** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
palmtreeee, @EronTo, @tajohnson661, @a1300, @Alecton4, @iiiyu, @guillermodulce, @anu82sharma12, @OmarMWarraich, @SHArPyCoBRA, @am1rasdi74, @taramakage, @sebastiantf, @Elldees, @Dcreo, @shanechioa, @keyliwen, @Flipstarter-Tool-Cash, @crzypatchwork, @sir4ju1, @MikuGhoul, @NoorahSmith, @jaiminpan, @yash-sharma1, @EmmaChanhy, @alexleventer, @kmes, @forever9teen, @Superoldman96, @suhdev, @YeautyYE, @KIssShot-Shinobu, @vladkudravtsev, @0x-tsar, @Starrpix, @reticenceji, @mhdigitalweb, @Talaqalotaibipmp, @MohameddAli, @liomen, @mortemn, @hstarorg, @Cctrip6g, @amusingaxl, @mjwaters, @rollfiend, @carloszimm, @kostjaigin, @boredavinci, @marcusbadillo
